.row.justify-content-center
  .col-sm-12.col-md-6
    h2 New Reads
    p This application will be a repository for books you own, much like a personal library, but now you can keep track of what you've read or keep details and reviews of ones you have..
    .list-group
      a.list-group-item.list-group-item-action href="/books" Your Books
      a.list-group-item.list-group-item-action href="#" TBD
